name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@master
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package --file pom.xml
    - uses: actions/upload-artifact@master
      with:
        name: RC24-Bot
        path: target/RC24-Bot.jar